default:
  # --- Параметри індикаторів ---
  fast_ema_period: 20       # Період для розрахунку швидкої експоненційної ковзної середньої (EMA).
  slow_ema_period: 50       # Період для розрахунку повільної експоненційної ковзної середньої (EMA).
  rsi_period: 14            # Період для розрахунку індексу відносної сили (RSI).
  volume_ma_period: 20      # Період для розрахунку ковзної середньої обсягу.
  atr_period: 14            # Період для розрахунку середнього істинного діапазону (ATR).
  adx_period: 14            # Період для розрахунку індикатора ADX.
  adx_threshold: 25         # Поріг ADX для фільтрації тренду.

  # --- Таймфрейм для аналізу ---
  kline_interval: '5m'     # Інтервал свічок, на якому працює стратегія.

  # --- Управління ризиками ---
  sl_atr_multiplier: 1.5    # Множник ATR для розрахунку Stop Loss.
  rr_ratio: 2.0             # Співвідношення ризик/прибуток.
  max_sl_percentage: 0.1    # Максимально допустимий Stop Loss у відсотках від ціни входу.

  # --- Додаткові фільтри та методи ---
  use_candle_patterns: true # Визначає, чи використовувати свічкові патерни.
  tp_method: 'rr_ratio'     # Метод розрахунку Take Profit.
  use_rsi_filter:  true    # Визначає, чи використовувати фільтр RSI.
  use_volume_filter: true  # Визначає, чи використовувати фільтр обсягу.
  use_adx_filter: true     # Визначає, чи використовувати фільтр ADX.
