default:
  # --- Параметри індикаторів ---
  fast_ema_period: 30       # Консервативний: Довший період для швидкої EMA.
  slow_ema_period: 80       # Консервативний: Довший період для повільної EMA.
  rsi_period: 14            # Період для розрахунку індексу відносної сили (RSI).
  volume_ma_period: 20      # Період для розрахунку ковзної середньої обсягу.
  atr_period: 14            # Період для розрахунку середнього істинного діапазону (ATR).
  adx_period: 14            # Період для розрахунку індикатора ADX.
  adx_threshold: 30         # Консервативний: Вищий поріг ADX для більш надійних сигналів.

  # --- Таймфрейм для аналізу ---
  kline_interval: '15m'    # Консервативний: Довший інтервал свічок.

  # --- Управління ризиками ---
  sl_atr_multiplier: 1.0    # Консервативний: Нижчий множник ATR для Stop Loss.
  rr_ratio: 1.5             # Консервативний: Нижче співвідношення ризик/прибуток.
  max_sl_percentage: 0.05   # Консервативний: Нижчий максимально допустимий Stop Loss.

  # --- Додаткові фільтри та методи ---
  use_candle_patterns: true # Визначає, чи використовувати свічкові патерни.
  tp_method: 'rr_ratio'     # Метод розрахунку Take Profit.
  use_rsi_filter:  true    # Визначає, чи використовувати фільтр RSI.
  use_volume_filter: true  # Визначає, чи використовувати фільтр обсягу.
  use_adx_filter: true     # Визначає, чи використовувати фільтр ADX.
  use_pullback_entry: false # Визначає, чи використовувати логіку входу на відкаті.
  pullback_ema_type: 'slow' # Тип EMA для відкату ('fast' або 'slow').
  pullback_tolerance_pct: 0.002 # Відсоток толерантності для відкату ціни до EMA.
