default:
  # --- Фільтри Індикаторів (налаштування для скальпінгу) ---
  ema_filter_enabled: true
  ema_period: 50 # Використовуємо коротшу EMA для реакції на локальні тренди, а не глобальні
  ema_timeframe: '5m'

  rsi_filter_enabled: true
  rsi_period: 14
  rsi_timeframe: '3m' # Короткий таймфрейм для швидкої оцінки імпульсу
  rsi_long_threshold: 70  # Дозволяємо вхід, навіть якщо ринок вже трохи розігрітий
  rsi_short_threshold: 30 # Дозволяємо вхід, навіть якщо ринок вже трохи охолов

  # --- Пошук "Стінок" (більш чутливі налаштування) ---
  wall_volume_multiplier: 7 # Робить стратегію більш чутливою до менших стінок
  activation_distance_ticks: 12 # Ціна повинна бути досить близько до стінки
  max_spread_bps: 3 # Критично для скальпінгу, щоб спред був мінімальним
  min_wall_volume: 7500 # Знижено для більшої кількості сигналів по менш ліквідним парам

  # --- Управління Ордерами (швидкий вхід/вихід) ---
  entry_offset_ticks: 1 # Входимо близько до стінки
  stop_loss_percent: 0.4 # Дуже жорсткий стоп-лос для мінімізації збитків
  initial_tp_min_search_percent: 0.3 # Мінімальна ціль по прибутку
  initial_tp_search_percent: 0.8 # Максимальна ціль по прибутку

  # --- Управління Позицією (агресивне) ---

  pre_emptive_close_threshold_mult: 1.5 # Більш чутливе закриття при зміні тиску в стакані

# --- Специфічні налаштування для символів (приклади для скальпінгу) ---
# Тут ви можете перевизначити будь-який з параметрів default для конкретної монети
