default:
  # --- Параметри індикаторів ---
  fast_ema_period: 10       # Агресивний: Коротший період для швидкої EMA.
  slow_ema_period: 30       # Агресивний: Коротший період для повільної EMA.
  rsi_period: 14            # Період для розрахунку індексу відносної сили (RSI).
  volume_ma_period: 20      # Період для розрахунку ковзної середньої обсягу.
  atr_period: 14            # Період для розрахунку середнього істинного діапазону (ATR).
  adx_period: 14            # Період для розрахунку індикатора ADX.
  adx_threshold: 20         # Агресивний: Нижчий поріг ADX для більш частих сигналів.

  # --- Таймфрейм для аналізу ---
  kline_interval: '5m'     # Інтервал свічок, на якому працює стратегія.

  # --- Управління ризиками ---
  sl_atr_multiplier: 2.0    # Агресивний: Вищий множник ATR для Stop Loss.
  rr_ratio: 2.5             # Агресивний: Вище співвідношення ризик/прибуток.
  max_sl_percentage: 0.15   # Агресивний: Вищий максимально допустимий Stop Loss.

  # --- Додаткові фільтри та методи ---
  use_candle_patterns: true # Визначає, чи використовувати свічкові патерни.
  tp_method: 'rr_ratio'     # Метод розрахунку Take Profit.
  use_rsi_filter:  true    # Визначає, чи використовувати фільтр RSI.
  use_volume_filter: true  # Визначає, чи використовувати фільтр обсягу.
  use_adx_filter: true     # Визначає, чи використовувати фільтр ADX.
  use_pullback_entry: true # Агресивний: Визначає, чи використовувати логіку входу на відкаті.
  pullback_ema_type: 'fast' # Тип EMA для відкату ('fast' або 'slow').
  pullback_tolerance_pct: 0.0005 # Агресивний: Менший відсоток толерантності для відкату ціни до EMA.
