
# Основний конфігураційний файл

# Список символів для моніторингу та торгівлі.
# Якщо список порожній, бот спробує завантажити всі доступні символи з біржі.
symbols: []

# Список стратегій, які бот буде запускати.
# Назви повинні відповідати назвам класів стратегій. DynamicOrderbookStrategy, EmaTrendFollowingStrategy
enabled_strategies:
  - EmaTrendFollowingStrategy

# Шляхи до файлів з налаштуваннями для кожної стратегії.
strategy_settings:
  EmaTrendFollowingStrategy: "configs/strategies/ema_trend_following.yaml"

# Загальні параметри торгівлі та ризик-менеджменту.
trading_parameters:
  margin_per_trade_pct: 0.1 # Відсоток від депозиту, що використовується для однієї угоди.
  fee_pct: 0.0004 # Комісія біржі у відсотках.
  leverage: 10 # Кредитне плече.
  margin_type: "ISOLATED" # Тип маржі (ISOLATED або CROSSED).
  max_active_trades: 10 # Максимальна кількість одночасно відкритих позицій.
  max_concurrent_symbols: 100 # Максимальна кількість символів для одночасного моніторингу.
  screener:
    min_volume: 50000000 # Мінімальний 24-годинний обсяг в USDT для включення символу в скринері.
