# ===============================================
# Налаштування за замовчуванням для всіх пар
# ===============================================
default:
  # У скільки разів об'єм лімітного ордеру має перевищувати середній, щоб вважатися "стіною".
  # Визначає, наскільки велику ліквідність ми шукаємо.
  wall_volume_multiplier: 10

  # Максимальна відстань до "стіни" (в тіках), при якій бот розглядає можливість входу.
  # Якщо ціна занадто далеко, стіна ігнорується.
  activation_distance_ticks: 15

  # На скільки тіків ПЕРЕД "стіною" виставляти лімітний ордер на вхід.
  # Дозволяє "зайти" в угоду перед тим, як ціна дійде до основного об'єму.
  entry_offset_ticks: 10

  # На скільки тіків ЗА "стіною" розміщувати стоп-лос.
  # Стіна виступає як захисний бар'єр.
  stop_loss_offset_ticks: 10

  # Цільове співвідношення ризику до прибутку (Risk/Reward Ratio).
  # Наприклад, 1.5 означає, що потенційний прибуток в 1.5 рази більший за потенційний збиток.
  risk_reward_ratio: 1.5

# =================================================================
# Індивідуальні налаштування для конкретних торгових пар
# Ключ повинен відповідати `params_key` з файлу strategies.json
# =================================================================
LiquidityHunting_ETHUSDT_DOM:
  # Приклад перевизначення параметрів для ETH.
  # Тут ми шукаємо ще більші стіни (множник 12) і очікуємо вищий прибуток (RRR 2.0).
  wall_volume_multiplier: 12
  risk_reward_ratio: 2.0