default:
  # Множник для визначення аномального об'єму
  volume_threshold_multiplier: 2.5
  # Відсоткове співвідношення тіла свічки до її загального розміру
  body_size_threshold_pct: 0.2
  # Кількість свічок для пошуку кульмінаційного бару
  climax_bar_lookback: 10
  # Множник ATR для розрахунку Take-Profit
  tp_atr_multiplier: 1.5
  # Період SMA для індикатора CVD
  cvd_sma_period: 5

  # Налаштування сигналів
  setups:
    exhaustion_short:
      enabled: true
      conditions:
        is_high_volume: true
        is_small_body: true
        is_new_high: true
        cvd_bearish_divergence: false
    exhaustion_long:
      enabled: true
      conditions:
        is_high_volume: true
        is_small_body: true
        is_new_low: true
        cvd_bullish_divergence: false
    absorption_short:
      enabled: true
      conditions:
        is_at_high: true
        is_high_volume: true
        is_rejection_from_high: true
        cvd_bearish_divergence: false
    absorption_long:
      enabled: true
      conditions:
        is_at_low: true
        is_high_volume: true
        is_rejection_from_low: true
        cvd_bullish_divergence: false

# Приклад індивідуальних налаштувань для конкретної торгової пари
OrderFlowScalping_LTCUSDT_1m:
  __comment__: "Тут ви можете перевизначити будь-які параметри для конкретної монети, наприклад, LTCUSDT. Якщо тут нічого не змінювати, будуть використовуватися значення з 'default'."
  # LTC більш волатильний, тому використовуємо вищий поріг об'єму
  volume_threshold_multiplier: 3.0
